### PR TITLE
Fixes purgecss for class detection inside Svelte components which use class directives

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by babichjacob** [comment]
Why thank you. I would like to see if it's possible to simplify this by combining these into one regex, but I don't plan on doing that tonight.

**Comment by ghost** [comment]
Yeah I tried but that's as far as I got.

**Comment by babichjacob** [comment]
As far as I'm aware, this can cover everything in a single line:

```js
defaultExtractor: (content) => [...content.matchAll(/(?:class:)*([\w\d-/:%.]+)/gm)].map((element) => element[1]),
```

Is there more rigorous testing this needs to go through than 
```html
<div class:centerer={true} class:hidden class:flex={!hidden}>
```
?

**Comment by babichjacob** [comment]
Included with f0d65d3

**Comment by ghost** [comment]
> As far as I'm aware, this can cover everything in a single line:
> 
> ```js
> defaultExtractor: (content) => [...content.matchAll(/(?:class:)*([\w\d-/:%.]+)/gm)].map((element) => element[1]),
> ```
> 
> Is there more rigorous testing this needs to go through than
> 
> ```
> <div class:centerer={true} class:hidden class:flex={!hidden}>
> ```
> 
> ?

No - that's about as much testing as I did with mine too. 💯

**Pull request closed without merging**
